// Generated by CoffeeScript 1.3.3
(function() {
  var $body, ie;

  if (window['ie'] != null) {
    ie = window.ie;
  }

  $body = $(document.body);

  window.log = function() {
    var newarr;
    log.history = log.history || [];
    log.history.push(arguments);
    if (this.console) {
      arguments.callee = arguments.callee.caller;
      newarr = [].slice.call(arguments);
      if (typeof console.log === 'object') {
        return log.apply.call(console.log, console, newarr);
      } else {
        return console.log.apply(console, newarr);
      }
    }
  };

  $.getStyle = function(url, callback) {
    $('head').append('<link rel="stylesheet" type="text/css" href="' + url + '">');
    if ($.isFunction(callback)) {
      return callback();
    }
  };

  $.getScript = function(url, callback, options) {
    var o;
    o = $.extend({}, options, {
      cache: true,
      dataType: 'script',
      url: url,
      success: callback,
      type: 'GET'
    });
    return $.ajax(o);
  };

  window.Site = {
    ie_fallback: function() {
      $('#header').prepend('<span class="bg"></span>');
      return $('input').filter('[type=radio]').addClass('radio').end().filter('[type=checkbox]').addClass('checkbox').end();
    },
    blank: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAMAAAAoyzS7AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF////AAAAVcLTfgAAAAF0Uk5TAEDm2GYAAAAMSURBVHjaYmAACDAAAAIAAU9tWeEAAAAASUVORK5CYII=',
    comic: function() {
      var $li, $nav, current, length, position, width;
      $nav = $('.comic-nav');
      $li = $nav.find('li');
      length = $li.length;
      width = ((50 + 4 + 15) * length) + 5;
      $nav.find('ul').css('width', width);
      current = $li.index($nav.find('li.current')) - 1;
      position = current === 0 ? 0 : (current / 100) * length;
      return FlowSlider('.comic-nav .bg', {
        marginEnd: 5,
        marginStart: 5,
        position: position,
        startPosition: 0.0
      });
    },
    comic_arrows: function() {
      var $arrow, $comic, $prev_next, fn, prev_offset, prev_offset2;
      $comic = $('#comic');
      $prev_next = $comic.find('a.prev');
      $prev_next = $prev_next.length ? $prev_next : $comic.find('a.next');
      $arrow = $prev_next.find('span');
      if (!$prev_next.length) {
        return;
      }
      prev_offset = $prev_next.offset().top + 100;
      prev_offset2 = ($prev_next.offset().top + $prev_next.outerHeight()) - ($arrow.outerHeight() + 100);
      fn = function(e) {
        var window_offset;
        window_offset = window.scrollY;
        if (window_offset >= prev_offset && window_offset <= prev_offset2) {
          return $comic.addClass('fixed-top').removeClass('fixed-bottom');
        } else if (window_offset >= prev_offset2) {
          return $comic.addClass('fixed-bottom').removeClass('fixed-top');
        } else {
          return $comic.removeClass('fixed-top').removeClass('fixed-bottom');
        }
      };
      $(window).on('scroll.comic', fn);
      return fn();
    },
    comments: function() {
      var $comments, $form_container;
      $comments = $('#comments');
      if ($comments.find('li.comment').length > Site.comments_pagination_number) {
        $.getScript('/js/jquery.jplist.3.3.min.js', function() {
          return Site.comments_pagination($comments);
        });
      }
      $comments.on('focus', 'a.comment-author, a.autor', function(e) {
        return $.scrollTo($(this).parents('.comment'), {
          axis: 'y',
          duration: 350,
          margin: true
        });
      });
      $form_container = $('#comments-form-container');
      return $form_container.on('click', 'a.login', function(e) {
        return $.scrollTo('#login-container', {
          axis: 'y',
          duration: 350,
          margin: true,
          callback: function() {
            return $('#login input[name=username]').trigger('focus');
          }
        });
      }).on('click', 'a.register', function(e) {
        return $.scrollTo('#register-container', {
          axis: 'y',
          duration: 350,
          margin: true,
          callback: function() {
            return $('#register-link').trigger('click');
          }
        });
      }).on('focus', 'textarea', function(e) {
        return $form_container.addClass('active');
      }).on('blur', 'textarea', function(e) {
        return $form_container.removeClass('active');
      });
    },
    comments_pagination_number: 25,
    comments_pagination: function($comments) {
      var $last, $pagination, pagination;
      pagination = '<div class="pagination pagination-js"></div>';
      $comments.prepend(pagination).append(pagination);
      $comments.find('li.comment').each(function(i) {
        return $(this).prepend('<span class="comment-order">' + (i + 1) + '</span>');
      });
      $comments.jplist({
        cookies: false,
        items_box: '#comments-list',
        items_on_page: Site.comments_pagination_number,
        item_path: 'li.comment',
        max_pages: 35,
        pagingbox: '.pagination',
        sort: {
          order: 'span.comment-order'
        },
        sort_is_num: true,
        sort_name: 'order'
      });
      $pagination = $comments.find('.pagination');
      $pagination.find('.prev').text('Anterior').before('&laquo;').prev().remove();
      $pagination.find('.next').text('Siguiente').after('&raquo;').next().remove();
      $last = $pagination.eq(0).find('#pagesbox span:last-child');
      $last.triggerHandler('click');
      return $pagination.eq(1).on('click.scroll', 'span', function(e) {
        return $.scrollTo($comments, {
          axis: 'y',
          duration: 350,
          margin: true
        });
      });
    },
    featured: function() {
      return $('.widget-featured .pagination span').live('mouseenter', function(e) {
        var $span, $widget;
        $span = $(this);
        $widget = $span.parents('.widget');
        if ($span.hasClass('alignright')) {
          return $widget.removeClass('widget-featured-first').addClass('widget-featured-last');
        } else {
          return $widget.removeClass('widget-featured-last').addClass('widget-featured-first');
        }
      });
    },
    lazyload: function(options) {
      var fn;
      if (options == null) {
        options = {};
      }
      fn = function() {
        var $img;
        $img = $('img[data-src]');
        $img.attr('src', Site.blank);
        $img.lazyload(options);
        return $(window).trigger('scroll');
      };
      if ($.fn.lazyload) {
        return $.getScript('/js/waypoints.min.js', function() {
          return $.getScript('/js/jquery.lazyload.js', fn);
        });
      } else {
        return fn();
      }
    },
    login: function() {
      var $register, $register_link;
      $('#login').find('input').bind('focus', function(e) {
        return $(this.form).addClass('focus');
      }).end().find('.back').bind('click', function(e) {
        e.preventDefault();
        return $('#login').removeClass('focus');
      });
      $register = $('#register');
      $register_link = $('#register-link');
      $register_link.bind('click mouseenter', function(e) {
        e.preventDefault();
        $(this).add($register).addClass('active');
        return $('#register-username').focus();
      });
      return $register.find('.close').bind('click', function(e) {
        $register_link.removeClass('active');
        return $register.animate({
          opacity: 0
        }, 150, function() {
          return $(this).removeClass('active').removeAttr('style');
        });
      });
    },
    mobile: function() {
      return navigator.appVersion.toLowerCase().indexOf("mobile") > -1;
    },
    notifications: function() {
      var $notibutton, $notif, $notinav, classname, d, data, html, i, text;
      $notif = $("#notifications");
      $notinav = $notif.find('nav');
      $notibutton = $('#cantidad_notificaciones');
      $notibutton.on('click', function(e) {
        e.preventDefault();
        $notinav.slideDown();
        $notif.on('click', function(e) {
          return e.stopPropagation();
        });
        return $body.on('click', function() {
          return $notinav.slideUp();
        });
      });
      data = window.notifications;
      if ((data != null) && data.total) {
        html = '';
        for (i in data) {
          d = data[i];
          if (i === 'total') {
            continue;
          }
          classname = i % 2 ? 'even' : 'odd';
          switch (d.tipo) {
            case 0:
              classname += ' notification-mp';
              text = " Nuevo mensaje <br /><a href=\"" + d.url + "\">" + d.titulo + "</a> de " + d.URLUserName + " ";
              break;
            case 1:
              classname += ' notification-ego';
              text = " Nuevas respuestas en <br /><a href=\"" + d.url + "\">" + d.titulo + "</a> ";
              break;
            case 2:
              classname += ' notification-blog';
              text = " Art&iacute;culo: <br /><a href=\"" + d.url + "\">" + d.titulo + "</a> ";
          }
          html += " <li class=\"" + classname + "\">" + text + "</li> ";
        }
        $notibutton.text(data.total);
        $notif.find('ul').append(html);
        $notif.show();
      }
    },
    prettify: function() {
      var cache;
      cache = {
        o: {},
        lang: [],
        files: []
      };
      $('.prettyprint[data-lang]').each(function(i) {
        var $pre, lang;
        $pre = $(this);
        lang = $pre.data('lang');
        if (!lang || cache.o[lang]) {
          return;
        }
        cache.o[lang] = 1;
        cache.lang.push(lang);
        if (lang === 'css' || lang === 'sql') {
          return cache.files.push('http://google-code-prettify.googlecode.com/svn/trunk/src/lang-' + lang + '.js');
        }
      });
      return Modernizr.load([
        {
          load: cache.files,
          complete: function() {
            return prettyPrint();
          }
        }
      ]);
    },
    prettify_admin: function() {
      var $select, new_theme, theme;
      theme = $.cookie('prettify_theme');
      new_theme = null;
      $select = $('#prettify-themes select').on('change', function() {
        new_theme = $select.val();
        return $('#prettify-' + new_theme).addClass('active').siblings('.active').removeClass();
      });
      if (theme) {
        $select.find('option[selected]').removeAttr('selected');
        $select.find('option[value=' + theme + ']').attr('selected', 'selected');
        $select.trigger('change');
      }
      return $($select[0].form).on('submit', function() {
        if (new_theme) {
          return $.cookie('prettify_theme', new_theme, {
            expires: 365,
            domain: 'cristalab.com',
            path: '/'
          });
        }
      });
    },
    prettify_theme: function() {
      var theme;
      theme = $.cookie('prettify_theme');
      if (theme) {
        $body.removeClass('prettify-primavera');
        return $body.addClass('prettify-' + theme);
      }
    },
    sisyphus: function() {
      if ($('#comments-form form').length) {
        $('#comments-form form').sisyphus();
      }
      if ($('#publicar-form').length) {
        return $('#publicar-form').sisyphus();
      }
    },
    stickySidebar: function() {
      var $container, $sidebar, fixed, fn, height, top;
      fixed = false;
      $sidebar = $('#sidebar');
      if (!$sidebar.length) {
        return;
      }
      $container = $sidebar.parent();
      top = $sidebar.offset().top;
      height = $sidebar.outerHeight();
      fn = function(e) {
        var offset, parent_offset;
        parent_offset = ($container.offset().top + $container.height()) - height;
        offset = window.pageYOffset;
        if (offset >= parent_offset) {
          $sidebar.removeClass('fixed-top').addClass('fixed-bottom');
          fixed = false;
          return;
        }
        if (!fixed && offset >= top) {
          $sidebar.removeClass('fixed-bottom').addClass('fixed-top');
          fixed = true;
        }
        if (fixed && offset <= top) {
          $sidebar.removeClass('fixed-top').removeClass('fixed-bottom');
          return fixed = false;
        }
      };
      $(window).bind('scroll.sidebar', fn);
      return fn();
    },
    tag: function() {
      return $('#content a.more').live('click', function(e) {
        var $link, $list;
        e.preventDefault();
        $link = $(this);
        $list = $link.data('list');
        if (!$list) {
          $list = $link.parent().next();
          $link.data('list', $list);
        }
        return $list.animate({
          height: 'toggle',
          opacity: 'toggle'
        }, 150);
      });
    },
    tutorials: function() {
      $('.tutorials-list-container').not('.videotutorials-list-container').on('click', 'a.more', function(e) {
        var $link, $list;
        e.preventDefault();
        $link = $(this);
        $list = $link.data('list');
        if (!$list) {
          $list = $link.parent().parent().next();
          $link.data('list', $list);
        }
        return $list.animate({
          height: 'toggle',
          opacity: 'toggle'
        }, 150);
      });
      return $('.videotutorials-list-container').on('click', 'a.more', function(e) {
        var $link, $list;
        e.preventDefault();
        $link = $(this);
        $list = $link.data('list');
        if (!$list) {
          $list = $link.parent().next();
          $link.data('list', $list);
        }
        return $list.animate({
          height: 'toggle',
          opacity: 'toggle'
        }, 150);
      });
    },
    videotutorials: function() {
      var $video_pagination;
      $video_pagination = $('.videotutorial-pagination');
      if (!$video_pagination.length) {
        return;
      }
      return $video_pagination.on('click', 'a', function(e) {
        var $link;
        e.preventDefault();
        $link = $(this);
        if ($link.hasClass('active')) {
          return;
        }
        $link.addClass('active').siblings('.active').removeClass().end();
        return $($link.data('video')).removeClass('videotutorial-player-inactive').siblings('.videotutorial-player').addClass('videotutorial-player-inactive').end();
      });
    },
    load: function() {
      if (!Site.mobile() && ($body.hasClass('blog-detail') || $body.hasClass('vertutorial') || $body.hasClass('vercurso'))) {
        Site.stickySidebar();
      }
      if ($('#comments-form form, #publicar-form').length) {
        $.getScript('/js/sisyphus.min.js', Site.sisyphus);
      }
      if ($('.comic-nav').length) {
        $.getScript('/js/flowslider.jquery.js', Site.comic);
      }
      if (!Site.mobile() && $('#comic .prev, #comic .next').length) {
        Site.comic_arrows();
      }
      return $.getScript('/js/jquery.cookie.js', function() {
        Site.prettify_theme();
        if ($('pre.prettyprint').length > 0) {
          $.getScript('http://google-code-prettify.googlecode.com/svn/trunk/src/prettify.js', Site.prettify);
        }
        if ($('#prettify-themes').length) {
          return Site.prettify_admin();
        }
      });
    },
    init: function() {
      if ($('#login-container').length) {
        Site.login();
      }
      Site.notifications();
      if ($('.widget-featured').length) {
        Site.featured();
      }
      if ($body.hasClass('videotutorial-single')) {
        Site.videotutorials();
      }
      if ($body.hasClass('tag-detail')) {
        Site.tag();
      }
      if ($body.hasClass('tutoriales')) {
        Site.tutorials();
      }
      if (ie <= 7) {
        Site.ie_fallback();
      }
      if ($('#comments').length) {
        $.getScript('/js/jquery.scrollTo-min.js', Site.comments);
      }
      return $(window).bind('load', Site.load);
    }
  };

  Site.init();

}).call(this);
